### ISSUE TITLE
ERROR: Net::SSH::HostKeyMismatch: fingerprint xx:76:xx:89:xx:c0:xx:75:xx:70:xx:26:xx:35:xx:2c does not match for "192.168.33.xx"

### ISSUE THREAD

**Issue by imamura-2ndwave** [starlod/develop#3]
```
$ chef exec knife solo prepare 192.168.33.xx
Bootstrapping Chef...
ERROR: Net::SSH::HostKeyMismatch: fingerprint xx:76:xx:89:xx:c0:xx:75:xx:70:xx:26:xx:35:xx:2c does not match for "192.168.33.xx"
```

**Comment by imamura-2ndwave** [comment]
このエラーは同じIPアドレスでサーバを立て直したときなどに起こります。
サーバを入れ替えるとホストキーが変わってしまうため、「同じIPなのにホストキーが以前と違う=乗っ取りの可能性がある」と判断されるようです。

サーバを入れ替えたことが確かな場合はchefサーバが記憶しているホストキーを削除することでこのエラーを回避することができます。

```
$ rm ~/.ssh/known_hosts
```

**Comment by imamura-2ndwave** [comment]
下記のコマンドを実行すれば、
`~/.ssh/known_hosts`からサーバー情報を削除して、
`~/.ssh/known_hosts.old`にサーバーの情報がバックアップされる。

```
$ ssh-keygen -R 192.168.33.xx
```

**Comment by starlod** [comment]
http://qiita.com/grgrjnjn/items/8ca33b64ea0406e12938
http://hacknote.jp/archives/5914/
